# Speciale matrices

Sommige speciale types van matrices zijn zeer bruikbaar in de context van Machine Learning.

## Vierkante matrix
Een **vierkante matrix** is een matrix met evenveel rijen als kolommen. **Een matrix $\pmb{V}_{m \times n}$ is vierkant als en slechts als $m = n$**.
Geometrisch gezien, doen ze dienst als transformatoren van vectoren, meer bepaald om die te schalen, reflecteren en/of te roteren. Welke transformatie precies gebeurt, kan afgeleid worden van de zogenaamde **determinant**.
In het geval van een $2 \times 2$ matrix (2D ruimte):
$$
\pmb{A} = \begin{bmatrix}
a & b \cr
c & d
\end{bmatrix}
$$
wordt de determinant $det(\pmb{A})$ bekomen door:
$$
det(\pmb{A}) = ad - bc
$$
In het geval van een $3 \times 3$ matrix (3D ruimte):
$$
\pmb{A} = \begin{bmatrix}
a & b & c \cr
d & e & f \cr
g & h & i
\end{bmatrix}
$$
is de formule iets complexer:
$$
det(\pmb{A}) = aei + bfg + cdh - ceg - bdi - afh
$$
Specifieke gevallen:
- $det(\pmb{A}) > 0$: Er gebeurt een schaling, maar zonder reflectie.
- $det(\pmb{A}) < 0$: Er gebeurt een schaling, inclusief reflectie.
- $det(\pmb{A}) = 1$: Afstanden en hoeken worden behouden, zonder reflectie.
- $det(\pmb{A}) = -1$: Afstanden en hoeken worden behouden en er gebeurt reflectie.
- $det(\pmb{A}) = 0$: De matrix drukt de ruimte samen naar een lagere dimensie $n-1$.

## Diagonale Matrix

Een **diagonale matrix** heeft niet-nul elementen alleen op de hoofddiagonaal. Alle _off_-diagonale elementen zijn nul. **Een matrix $\pmb{D}$ is diagonaal als en slechts als $D_{i,j} = 0$ voor alle $i \neq j$**.
$$
\pmb{D}_{m \times n} = \begin{bmatrix}
D_{1,1} & 0 & 0 & \ldots & 0 \cr
0 & D_{2,2} & 0 & \ldots & 0 \cr
0 & 0 & D_{3,3} & \ldots & 0 \cr
\vdots & \vdots & \vdots & \ddots & \vdots \cr
0 & 0 & 0 & \ldots & D_{n,n} \cr
0 & 0 & 0 & \ldots & 0 \cr
\vdots & \vdots & \vdots & \vdots & \vdots \cr
0 & 0 & 0 & \ldots & 0
\end{bmatrix}
$$

In [6]:
import numpy as np

In [17]:
# Create a diagonal matrix from a vector
diagonal_values = np.array([2, 5, 8])
D = np.diag(diagonal_values)
print("Diagonal Matrix:")
print(D)
print(f"\nDiagonal elements: {np.diag(D)}")

Diagonal Matrix:
[[2 0 0]
 [0 5 0]
 [0 0 8]]

Diagonal elements: [2 5 8]


## Identiteitsmatrix

Een **identiteitsmatrix is een _vierkante_ _diagonaal_ matrix met enkel de waarde $1$ op de hoofddiagonaal**.
$$
\pmb{I}_n = \begin{bmatrix}
1 & 0 & 0 & \ldots & 0 \cr
0 & 1 & 0 & \ldots & 0 \cr
0 & 0 & 1 & \ldots & 0 \cr
\vdots & \vdots & \vdots & \ddots & \vdots \cr
0 & 0 & 0 & \ldots & 1
\end{bmatrix}
$$

In [8]:
# Create a 3x3 identity matrix
I = np.eye(3)
print("3x3 Identity matrix:")
print(I)

3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Symmetrische Matrix

Een **symmetrische matrix is gelijk aan zijn transpose**:
$$
\pmb{A} = \pmb{A}^T
$$

In [18]:
# Create a symmetric matrix
S = np.array([[4, 2, 1], [2, 5, 3], [1, 3, 6]])
print("Symmetric Matrix:")
print(S)
print("\nTranspose:")
print(S.T)

Symmetric Matrix:
[[4 2 1]
 [2 5 3]
 [1 3 6]]

Transpose:
[[4 2 1]
 [2 5 3]
 [1 3 6]]


## _Upper triangular_ matrix

Een **_upper triangular_ matrix** is een vierkante matrix met alle elementen onder de hoofddiagonaal gelijk aan nul. **Een matrix $\pmb{U}^{m \times n}$ is een _upper triangular_ matrix als en slechts als $m = n$ en $U_{i,j} = 0$ voor alle $i < j$**
$$
\pmb{U}_n = \begin{bmatrix}
U_{1,1} & U_{1,2} & U_{1,3} & \ldots & U_{1,n} \cr
0 & U_{2,2} & U_{2,3} & \ldots & U_{2,n} \cr
0 & 0 & U_{3,3} & \ldots & U_{3,n} \cr
\vdots & \vdots & \vdots & \ddots & \vdots \cr
0 & 0 & 0 & \ldots & U_{n,n}
\end{bmatrix}
$$

In [20]:
# Create an upper triangular matrix from a full matrix
A = np.array([[4, 2, 1], [3, 5, 7], [1, 2, 9]])
U = np.triu(A)
print("Original Matrix:")
print(A)
print("\nUpper Triangular:")
print(U)

Original Matrix:
[[4 2 1]
 [3 5 7]
 [1 2 9]]

Upper Triangular:
[[4 2 1]
 [0 5 7]
 [0 0 9]]


## _Lower triangular_ matrix

Een **_lower triangular_ matrix** is een vierkante matrix met alle elementen boven de hoofddiagonaal gelijk aan nul. **Een matrix $\pmb{L}^{m \times n}$ is een _lower triangular_ matrix als en slechts als $m = n$ en $U_{i,j} = 0$ voor alle $i > j$**
$$
\pmb{L}_n = \begin{bmatrix}
D_{1,1} & 0 & 0 & \ldots & 0 \cr
D_{2,1} & D_{2,2} & 0 & \ldots & 0 \cr
D_{3,1} & D_{3,2} & D_{3,3} & \ldots & 0 \cr
\vdots & \vdots & \vdots & \ddots & \vdots \cr
D_{n,1} & D_{n,2} & D_{n,3} & \ldots & D_{n,n}
\end{bmatrix}
$$

In [22]:
# Create a lower triangular matrix
L = np.tril(A)
print("Original Matrix:")
print(A)
print("\nLower Triangular:")
print(L)

Original Matrix:
[[4 2 1]
 [3 5 7]
 [1 2 9]]

Lower Triangular:
[[4 0 0]
 [3 5 0]
 [1 2 9]]


## Orthogonale matrix

Een **orthogonale of orthonormale matrix** is een vierkante matrix waarbij de rijen en kolommen orthonomale vectoren zijn. Dit impliceert dat:
$$
\pmb{Q}^T\pmb{Q} = \pmb{Q}\pmb{Q}^T = \pmb{I}
$$
Geometrisch gezien, behouden orthogonale matrices afstanden en hoeken. Wanneer we het inner product nemen van de matrix met een reeks vectoren, behouden de resulterende vectoren hun lengte en onderlinge hoeken. Er kan wel een reflectie optreden:
$$
det(\pmb{Q}) \isin \{-1, 1\}
$$

## Rotatie matrix
Een rotatie matrix is een orthogonale matrix waarbij de determinant $1$ is. Wanneer we het inner product nemen van de matrix met een reeks vectoren, behouden de resulterende vectoren hun lengte en onderlinge hoeken én zal er géén reflectie optreden.
$$
det(\pmb{R}) = 1
$$