# Lineare algebra #1

In [1]:
import numpy as np

## Numerieke primitieven
### Scalairen
$$a = 5$$

In [2]:
a = np.array(5)
print(a)
print(a.dtype)
print(a.shape)
print(a.__class__.__name__)

5
int64
()
ndarray


$$a = 3.0$$

In [3]:
a = np.array(3.0)
print(a)
print(a.dtype)

3.0
float64


### Vectoren

$$
\pmb{a} = \begin{bmatrix}
5 \cr
8 \cr
12
\end{bmatrix}
$$

In [43]:
a = np.array([5, 8, 12])
print(a)
print(a.shape)

[ 5  8 12]
(3,)


Representatie als een kolom-vector (een matrix met 1 kolom):

In [44]:
a.reshape(3, 1)

array([[ 5],
       [ 8],
       [12]])

Representatie als een rij-vector (een matrix met 1 _rij_):

$$
\pmb{a}^T = \begin{bmatrix}
5 & 8 & 12
\end{bmatrix}
$$

In [45]:
a.reshape(1, 3)

array([[ 5,  8, 12]])

Transpositie terug naar kolom-vector:

In [46]:
a.reshape(1, 3).T

array([[ 5],
       [ 8],
       [12]])

### Matrices

$$
\pmb{B} = \begin{bmatrix}
1.0 & 2.0 & 3.0 \cr
7.0 & 1.0 & 2.0
\end{bmatrix}
$$

In [51]:
b = np.array([[1.0, 2.0, 3.0], [7.0, 1.0, 2.0]])
print(f"b: {b}")
print(f"b shape: {b.shape}")

b: [[1. 2. 3.]
 [7. 1. 2.]]
b shape: (2, 3)


$$
\pmb{B}^T
$$

In [53]:
print(b.T)

[[1. 7.]
 [2. 1.]
 [3. 2.]]


### Tensors

$$
\pmb{C} = \begin{bmatrix}
\begin{bmatrix}
1.0 & 2.0 & 3.0 \cr
7.0 & 1.0 & 2.0
\end{bmatrix}, \cr
\begin{bmatrix}
5.0 & 1.0 & 3.0 \cr
2.0 & 9.0 & 6.0
\end{bmatrix}
\end{bmatrix}
$$

In [55]:
c = np.array([[[1.0, 2.0, 3.0], [7.0, 1.0, 2.0]], [[5.0, 1.0, 3.0], [2.0, 9.0, 6.0]]])
print(f"c: {c}")
print(f"c shape: {c.shape}")

c: [[[1. 2. 3.]
  [7. 1. 2.]]

 [[5. 1. 3.]
  [2. 9. 6.]]]
c shape: (2, 2, 3)


In [ ]:
# Reshape the 3D array
c.reshape(3, 2, 2)

array([[[1., 2.],
        [3., 7.]],

       [[1., 2.],
        [5., 1.]],

       [[3., 2.],
        [9., 6.]]])

In [61]:
# 4D tensor with random values
rng = np.random.default_rng(12345)
d = rng.random((5, 3, 2, 3))
print(d)

[[[[0.22733602 0.31675834 0.79736546]
   [0.67625467 0.39110955 0.33281393]]

  [[0.59830875 0.18673419 0.67275604]
   [0.94180287 0.24824571 0.94888115]]

  [[0.66723745 0.09589794 0.44183967]
   [0.88647992 0.6974535  0.32647286]]]


 [[[0.73392816 0.22013496 0.08159457]
   [0.1598956  0.34010018 0.46519315]]

  [[0.26642103 0.8157764  0.19329439]
   [0.12946908 0.09166475 0.59856801]]

  [[0.8547419  0.60162124 0.93198836]
   [0.72478136 0.86055132 0.9293378 ]]]


 [[[0.54618601 0.93767296 0.49498794]
   [0.27377318 0.45177871 0.66503892]]

  [[0.33089093 0.90345401 0.25707418]
   [0.33982834 0.2588534  0.35544648]]

  [[0.00502233 0.62860454 0.28238271]
   [0.06808769 0.61682898 0.17632632]]]


 [[[0.30438839 0.44088681 0.15020234]
   [0.21792886 0.47433312 0.47636886]]

  [[0.25523235 0.29756527 0.27906712]
   [0.26057921 0.48276159 0.21197904]]

  [[0.4956306  0.24626133 0.83848265]
   [0.18013059 0.86215629 0.17829944]]]


 [[[0.75053133 0.6111204  0.20915503]
   [0.75987242 0.2

In [62]:
# Subtract two 4D tensors
g = rng.random((5, 3, 2, 3))
print(f"(d - g).shape: {(d - g).shape}")

(d - g).shape: (5, 3, 2, 3)


In [63]:
h = g.reshape((3, 3, 2, 5))

In [64]:
j = g.reshape((3, 3 * 2 * 5))

In [65]:
print((d - h).shape)

ValueError: operands could not be broadcast together with shapes (5,3,2,3) (3,3,2,5) 

In [66]:
print((d - j).shape)

ValueError: operands could not be broadcast together with shapes (5,3,2,3) (3,30) 

## Element-gewijse operaties  
$$
\pmb{a} = \begin{bmatrix}
5 \cr
8 \cr
12
\end{bmatrix}
$$
$$
\pmb{a} + 5
$$

In [67]:
print(f"a: {a}")
print(f"a+5: {a + 5}")

a: [ 5  8 12]
a+5: [10 13 17]


$$
\pmb{a} \times 5
$$

In [76]:
print(f"a x 5: {a * 5}")

a x 5: [25 40 60]


$$
\pmb{b} = \begin{bmatrix}
1 \cr
2 \cr
3
\end{bmatrix}
$$

$$
\pmb{a} + \pmb{b}
$$

In [69]:
b = np.array([1, 2, 3])
print(f"a + b: {a + b}")

a + b: [ 6 10 15]


Let op voor dimensies!

In [70]:
b = np.array([1, 2, 3, 4])
print(f"a + b: {a + b}")

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

$$
\pmb{a} \odot \pmb{b}
$$

In [71]:
b = np.array([1, 2, 3])
print(f"a * b: {a * b}")

a * b: [ 5 16 36]


$$
\pmb{A} = \begin{bmatrix}
1 & 2 \cr
3 & 4 \cr
5 & 6
\end{bmatrix}
$$

$$
\pmb{A}+5
$$

In [77]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(f"A: {A}")
print(f"A + 5: {A + 5}")

A: [[1 2]
 [3 4]
 [5 6]]
A + 5: [[ 6  7]
 [ 8  9]
 [10 11]]


$$
\pmb{A} \times 5
$$

In [78]:
print(f"A x 5: {A * 5}")

A x 5: [[ 5 10]
 [15 20]
 [25 30]]


$$
\pmb{B} = \begin{bmatrix}
5 & 3 \cr
3 & 1 \cr
9 & 0
\end{bmatrix}
$$

$$
\pmb{A}+\pmb{B}
$$

In [79]:
B = np.array([[5, 3], [3, 1], [9, 0]])
print(f"A: {A}")
print(f"B: {B}")
print(f"A + B: {A + B}")

A: [[1 2]
 [3 4]
 [5 6]]
B: [[5 3]
 [3 1]
 [9 0]]
A + B: [[ 6  5]
 [ 6  5]
 [14  6]]


$$
\pmb{A} \odot \pmb{B}
$$

In [80]:
print(f"A * B: {A * B}")

A * B: [[ 5  6]
 [ 9  4]
 [45  0]]


$$
\pmb{A}^T + \pmb{b}
$$

In [81]:
print(f"A: {A}")
print(f"b: {b}")

A: [[1 2]
 [3 4]
 [5 6]]
b: [1 2 3]


In [ ]:
print(A + b)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [ ]:
print(A.T + b)

[[2 5 8]
 [3 6 9]]


$$
\pmb{A}^T \odot \pmb{b}
$$

## _Dot_ product

$$
\begin{aligned}
\pmb{a} &= \begin{bmatrix}7 & 3 & 2\end{bmatrix}^T \cr
\pmb{b} &= \begin{bmatrix}2 & 8 & 1\end{bmatrix}^T \cr
\pmb{a}^T\pmb{b} &= \ldots
\end{aligned}
$$

$$
\begin{aligned}
\pmb{a} &= \begin{bmatrix}4.6 & 1.1 & 5.3 & 8.2 & 10.1\end{bmatrix}^T \cr
\pmb{b} &= \begin{bmatrix}6.1 & 1.5 & 3.5 & 7.9 & 2.8\end{bmatrix}^T \cr
\pmb{a}^T\pmb{b} &= \ldots
\end{aligned}
$$

$$
\begin{aligned}
\pmb{a} &= \begin{bmatrix}6 & 1 & 2 & 7\end{bmatrix}^T \cr
\pmb{b} &= \begin{bmatrix}2 & 2 & 1\end{bmatrix}^T \cr
\pmb{a}^T\pmb{b} &= \ldots
\end{aligned}
$$

$$
\begin{aligned}
\pmb{A} &=
\begin{bmatrix}
3 & 3 & 2 & 7 \cr
1 & 4 & 7 & 5 \cr
9 & 2 & 8 & 3
\end{bmatrix} \cr
\pmb{b} &= \begin{bmatrix}4 & 2 & 8 & 1\end{bmatrix}^T \cr
\pmb{A}\pmb{b} &= \ldots
\end{aligned}
$$

$$
\begin{aligned}
\pmb{A} &=
\begin{bmatrix}
6.1 & 3.7 \cr
1.0 & 4.3 \cr
5.1 & 3.3 \cr
3.9 & 3.7 \cr
7.9 & 8.2 \cr
\end{bmatrix} \cr
\pmb{b} &= \begin{bmatrix}3.0 & 2.2\end{bmatrix}^T \cr
\pmb{A}\pmb{b} &= \ldots
\end{aligned}
$$

$$
\begin{aligned}
\pmb{A} &=
\begin{bmatrix}
3 & 3 & 2 & 7 \cr
1 & 4 & 7 & 5 \cr
9 & 2 & 8 & 3
\end{bmatrix} \cr
\pmb{B} &=
\begin{bmatrix}
6 & 2 \cr
1 & 7 \cr
2 & 2 \cr
7 & 5
\end{bmatrix} \cr
\pmb{A}\pmb{B} &= \ldots
\end{aligned}
$$

Bereken het gemiddelde van de reeks $0$ tot en met $113$ aan de hand van een _dot_ product.

$$
\begin{aligned}
\pmb{a} &= \begin{bmatrix}5 & 3 & 2 & 9 & 2\end{bmatrix}^T \cr
||\pmb{a}||_2 &= \ldots
\end{aligned} 
$$

Hoe groot is de cosine similarity tussen:

$$
\begin{aligned}
\pmb{a} &= \begin{bmatrix}4.6 & 1.1 & 5.3 & 8.2 & 10.1\end{bmatrix}^T \cr
\pmb{b} &= \begin{bmatrix}6.1 & 1.5 & 3.5 & 7.9 & 2.8\end{bmatrix}^T \cr
\end{aligned}
$$

## 