# Lineare algebra in Python

Hier gaan we voorbeelden behandelen van alle elementen uit de les.

In [1]:
import numpy as np

## Numerieke primitieven
### Scalairen
$$a = 5$$

In [2]:
a = np.array(5)
print(a)
print(a.dtype)
print(a.shape)
print(a.__class__.__name__)

5
int64
()
ndarray


$$a = 3.0$$

In [3]:
a = np.array(3.0)
print(a)
print(a.dtype)

3.0
float64


### Vectoren

$$
\pmb{a} = \begin{bmatrix}
5 \cr
8 \cr
12
\end{bmatrix}
$$

In [10]:
a = np.array([5, 8, 12])
print(a)
print(a.shape)

[ 5  8 12]
(3,)


Als een kolom-vector (een matrix met 1 kolom)

In [11]:
a.reshape(3, 1)

array([[ 5],
       [ 8],
       [12]])

Als een rij-vector (een matrix met 1 _rij_)

$$
\pmb{a}^T = \begin{bmatrix}
5 & 8 & 12
\end{bmatrix}
$$

In [12]:
a.reshape(1, 3)

array([[ 5,  8, 12]])

Transpositie terug naar kolom-vector.

In [15]:
a.reshape(1, 3).T

array([[ 5],
       [ 8],
       [12]])

Basis operaties  
  
$$
\pmb{a} + 5
$$

In [ ]:
print(f"a: {a}")
print(f"a+5: {a + 5}")

a: [ 5  8 12]
a+5: [10 13 17]


$$
\pmb{a} * 5
$$

In [27]:
print(f"a * 5: {a * 5}")

a * 5: [25 40 60]


$$
\pmb{b} = \begin{bmatrix}
1 \cr
2 \cr
3
\end{bmatrix}
$$

$$
\pmb{a} + \pmb{b}
$$

In [ ]:
b = np.array([1, 2, 3])
print(f"a + b: {a + b}")

a + b: [ 6 10 15]


Let op voor dimensies!

In [ ]:
b = np.array([1, 2, 3, 4])
print(f"a + b: {a + b}")

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

$$
\pmb{a}*\pmb{b}
$$

In [32]:
b = np.array([1, 2, 3])
print(f"a * b: {a * b}")

a * b: [ 5 16 36]


### Matrices

$$
\pmb{B} = \begin{bmatrix}
1.0 & 2.0 & 3.0 \cr
7.0 & 1.0 & 2.0
\end{bmatrix}
$$

In [ ]:
b = np.array([[1.0, 2.0, 3.0], [7.0, 1.0, 2.0]])
print(b)
print(b.shape)

[[1. 2. 3.]
 [7. 1. 2.]]
(2, 3)


$\pmb{B}^T$

In [16]:
b.T

array([[1., 7.],
       [2., 1.],
       [3., 2.]])

### Tensors

$$
\pmb{C} = \begin{bmatrix}
\begin{bmatrix}
1.0 & 2.0 & 3.0 \cr
7.0 & 1.0 & 2.0
\end{bmatrix}, \cr
\begin{bmatrix}
5.0 & 1.0 & 3.0 \cr
2.0 & 9.0 & 6.0
\end{bmatrix}
\end{bmatrix}
$$

In [ ]:
c = np.array([[[1.0, 2.0, 3.0], [7.0, 1.0, 2.0]], [[5.0, 1.0, 3.0], [2.0, 9.0, 6.0]]])
print(c)
print(c.shape)

[[[1. 2. 3.]
  [7. 1. 2.]]

 [[5. 1. 3.]
  [2. 9. 6.]]]
(2, 2, 3)


In [18]:
c.reshape(3, 2, 2)

array([[[1., 2.],
        [3., 7.]],

       [[1., 2.],
        [5., 1.]],

       [[3., 2.],
        [9., 6.]]])

In [22]:
rng = np.random.default_rng(12345)
d = rng.random((5, 3, 2, 3))
print(d)

[[[[0.22733602 0.31675834 0.79736546]
   [0.67625467 0.39110955 0.33281393]]

  [[0.59830875 0.18673419 0.67275604]
   [0.94180287 0.24824571 0.94888115]]

  [[0.66723745 0.09589794 0.44183967]
   [0.88647992 0.6974535  0.32647286]]]


 [[[0.73392816 0.22013496 0.08159457]
   [0.1598956  0.34010018 0.46519315]]

  [[0.26642103 0.8157764  0.19329439]
   [0.12946908 0.09166475 0.59856801]]

  [[0.8547419  0.60162124 0.93198836]
   [0.72478136 0.86055132 0.9293378 ]]]


 [[[0.54618601 0.93767296 0.49498794]
   [0.27377318 0.45177871 0.66503892]]

  [[0.33089093 0.90345401 0.25707418]
   [0.33982834 0.2588534  0.35544648]]

  [[0.00502233 0.62860454 0.28238271]
   [0.06808769 0.61682898 0.17632632]]]


 [[[0.30438839 0.44088681 0.15020234]
   [0.21792886 0.47433312 0.47636886]]

  [[0.25523235 0.29756527 0.27906712]
   [0.26057921 0.48276159 0.21197904]]

  [[0.4956306  0.24626133 0.83848265]
   [0.18013059 0.86215629 0.17829944]]]


 [[[0.75053133 0.6111204  0.20915503]
   [0.75987242 0.2

In [35]:
g = rng.random((5, 3, 2, 3))
print((d - g).shape)

(5, 3, 2, 3)


In [36]:
h = g.reshape((3, 3, 2, 5))

In [ ]:
j = g.reshape((3, 3 * 2 * 5))

In [41]:
print((d - h).shape)

ValueError: operands could not be broadcast together with shapes (5,3,2,3) (3,3,2,5) 

In [42]:
print((d - j).shape)

ValueError: operands could not be broadcast together with shapes (5,3,2,3) (3,30) 