# Numpy
[^bron]
[^bron]: Gebaseerd op [cs231n.github.io/python-numpy-tutorial](https://cs231n.github.io/python-numpy-tutorial/#numpy)

Numpy is dé library voor wetenschappelijk rekenen in Python. Het biedt een hoogperformant multidimensioneel array object, en tools om met deze objecten te werken.

Om Numpy te gebruiken, moeten we eerst het `numpy` package importeren:

In [112]:
import numpy as np

## Arrays

Een numpy array is een raster van waarden, allemaal van hetzelfde type, en wordt geïndexeerd aan de hand van integers. De _shape_ van een array is een tuple van integers die de grootte van de array langs elke dimensie aangeeft.

In [192]:
# Create a vector
a = np.array([1, 2, 3])
print(a)
print(f"type(a): {type(a)}\na.shape: {a.shape}\na[0]: {a[0]}\na[1]: {a[1]}\na[2]: {a[2]}")


[1 2 3]
type(a): <class 'numpy.ndarray'>
a.shape: (3,)
a[0]: 1
a[1]: 2
a[2]: 3


In [193]:
# Change an element of the array
a[0] = 5
print(a)

[5 2 3]


In [ ]:
# Create a rank 2 array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(
    f"type(b): {type(b)}\nb.shape: {b.shape}\nb[0, 0]: {b[0, 0]}\nb[0, 2]: {b[0, 2]}\nb[1, 0]: {b[1, 0]}"
)

[[1 2 3]
 [4 5 6]]
type(b): <class 'numpy.ndarray'>
b.shape: (2, 3)
b[0, 0]: 1
b[0, 2]: 3
b[1, 0]: 4


Indexatie kan ook gebeuren aan de hand van tuples van integers waardoor we de indexatie via variabelen kunnen doen.

In [196]:
index = (0, 2)
print(b[index])

3


Er zijn ook talrijke functies om speciale matrices te creëren op basis van shape tuples.

In [ ]:
# Create an array of all zeros
a = np.zeros((3, 2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# Create an array of all ones
b = np.ones((4, 5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Create a constant array
c = np.full((2, 3), 7)
print(c)

[[7 7 7]
 [7 7 7]]


In [ ]:
# Create a 5x5 identity matrix
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Create an array filled with random values
rng = np.random.default_rng()  # Create a random number generator
e = rng.random((2, 3))
print(e)

[[0.2848079  0.92009732 0.14159273]
 [0.37762878 0.48835331 0.63026808]]


## Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [188]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [189]:
print(a[0, 1])
b[0, 0] = 77  # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

2
77


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [123]:
row_r1 = a[1, :]  # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [124]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [125]:
a = np.array([[1, 2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [126]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [127]:
# Create a new array from which we will select elements
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [128]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [129]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [130]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

bool_idx = a > 2  # Find the elements of a that are bigger than 2;
# this returns a numpy array of Booleans of the same
# shape as a, where each slot of bool_idx tells
# whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [131]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

## Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [132]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

## Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [133]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [134]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [135]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [136]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [137]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [138]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [139]:
print(v @ w)

219


In [140]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [141]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [142]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [143]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [144]:
v = np.array([[1, 2, 3]])
print(v)
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [145]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)  # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [146]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)  # Prints "[[1 0 1]
#          [1 0 1]
#          [1 0 1]
#          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [147]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [148]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [149]:
# Compute outer product of vectors
v = np.array([1, 2, 3])  # v has shape (3,)
w = np.array([4, 5])  # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [150]:
# Add a vector to each row of a matrix
x = np.array([[1, 2, 3], [4, 5, 6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [151]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [152]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [153]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

## Lineaire Algebra met Numpy

Numpy biedt krachtige functies voor lineaire algebra operaties die essentieel zijn voor machine learning. Hier zijn enkele belangrijke functies:

### Vector en Matrix Normen

De norm van een vector of matrix is een maat voor de "grootte". De meest gebruikte normen zijn:

In [154]:
# Vector normen
v = np.array([3, 4])
print(f"Vector: {v}")
print(f"L2 norm (Euclidean): {np.linalg.norm(v)}")
print(f"L1 norm (Manhattan): {np.linalg.norm(v, ord=1)}")
print(f"L∞ norm (Maximum): {np.linalg.norm(v, ord=np.inf)}")

# Matrix normen
A = np.array([[1, 2], [3, 4]])
print(f"\nMatrix:\n{A}")
print(f"Frobenius norm: {np.linalg.norm(A, 'fro')}")

Vector: [3 4]
L2 norm (Euclidean): 5.0
L1 norm (Manhattan): 7.0
L∞ norm (Maximum): 4.0

Matrix:
[[1 2]
 [3 4]]
Frobenius norm: 5.477225575051661


### Determinant

De determinant van een matrix geeft informatie over de lineaire transformatie die de matrix representeert:

In [155]:
A = np.array([[1, 2], [3, 4]])
det_A = np.linalg.det(A)
print(f"Matrix A:\n{A}")
print(f"Determinant: {det_A}")

# Een matrix met determinant 0 is singulier (niet inverteerbaar)
B = np.array([[1, 2], [2, 4]])
det_B = np.linalg.det(B)
print(f"\nMatrix B:\n{B}")
print(f"Determinant: {det_B} (singulier!)")

Matrix A:
[[1 2]
 [3 4]]
Determinant: -2.0000000000000004

Matrix B:
[[1 2]
 [2 4]]
Determinant: 0.0 (singulier!)


### Matrix Inverse

De inverse van een matrix A is een matrix A⁻¹ zodat A × A⁻¹ = I (identiteitsmatrix):

In [156]:
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)

print(f"Matrix A:\n{A}")
print(f"\nInverse A⁻¹:\n{A_inv}")

# Verificatie: A × A⁻¹ should be identity matrix
identity_check = A @ A_inv
print(f"\nA × A⁻¹ (should be identity):\n{identity_check}")
print(f"\nIdentity matrix:\n{np.eye(2)}")

Matrix A:
[[1 2]
 [3 4]]

Inverse A⁻¹:
[[-2.   1. ]
 [ 1.5 -0.5]]

A × A⁻¹ (should be identity):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Identity matrix:
[[1. 0.]
 [0. 1.]]


### Eigenwaarden en Eigenvectoren

Eigenwaarden en eigenvectoren zijn fundamenteel in lineaire algebra en machine learning:

In [157]:
A = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"Matrix A:\n{A}")
print(f"\nEigenwaarden: {eigenvalues}")
print(f"\nEigenvectoren:\n{eigenvectors}")

# Verificatie: A × v = λ × v voor elke eigenwaarde λ en eigenvector v
for i in range(len(eigenvalues)):
    lambda_i = eigenvalues[i]
    v_i = eigenvectors[:, i]

    left_side = A @ v_i
    right_side = lambda_i * v_i

    print(f"\nEigenwaarde {i + 1}: {lambda_i:.3f}")
    print(f"A × v = {left_side}")
    print(f"λ × v = {right_side}")
    print(f"Verschil: {np.allclose(left_side, right_side)}")

Matrix A:
[[4 2]
 [1 3]]

Eigenwaarden: [5. 2.]

Eigenvectoren:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

Eigenwaarde 1: 5.000
A × v = [4.47213595 2.23606798]
λ × v = [4.47213595 2.23606798]
Verschil: True

Eigenwaarde 2: 2.000
A × v = [-1.41421356  1.41421356]
λ × v = [-1.41421356  1.41421356]
Verschil: True


### Lineaire Systemen Oplossen

Voor het oplossen van lineaire systemen van de vorm Ax = b:

In [158]:
# Stel we hebben het systeem:
# 2x + 3y = 7
# x + 4y = 6

A = np.array([[2, 3], [1, 4]])
b = np.array([7, 6])

# Oplossen met np.linalg.solve
x = np.linalg.solve(A, b)
print(f"Coëfficiënten matrix A:\n{A}")
print(f"Constanten vector b: {b}")
print(f"Oplossing x: {x}")

# Verificatie
verification = A @ x
print(f"\nVerificatie A × x = {verification}")
print(f"Should equal b = {b}")
print(f"Correct: {np.allclose(verification, b)}")

Coëfficiënten matrix A:
[[2 3]
 [1 4]]
Constanten vector b: [7 6]
Oplossing x: [2. 1.]

Verificatie A × x = [7. 6.]
Should equal b = [7 6]
Correct: True


### Singular Value Decomposition (SVD)

SVD is een krachtige matrix factorization techniek die veel gebruikt wordt in machine learning:

In [159]:
# Maak een voorbeeldmatrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(f"Original matrix A ({A.shape}):\n{A}")

# SVD: A = U × Σ × V^T
U, s, Vt = np.linalg.svd(A)

print(f"\nU shape: {U.shape}")
print(f"s (singular values): {s}")
print(f"Vt shape: {Vt.shape}")

# Reconstructie van de originele matrix
# We moeten s omzetten naar een diagonale matrix van de juiste grootte
S = np.zeros((U.shape[1], Vt.shape[0]))
S[: len(s), : len(s)] = np.diag(s)

A_reconstructed = U @ S @ Vt
print(f"\nReconstructed matrix:\n{A_reconstructed}")
print(f"\nReconstruction accurate: {np.allclose(A, A_reconstructed)}")

Original matrix A ((4, 3)):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

U shape: (4, 4)
s (singular values): [2.54624074e+01 1.29066168e+00 2.40694596e-15]
Vt shape: (3, 3)

Reconstructed matrix:
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]

Reconstruction accurate: True


### Matrix Rank

De rank van een matrix geeft het aantal lineair onafhankelijke rijen of kolommen aan:

In [160]:
# Full rank matrix
A = np.array([[1, 2], [3, 4]])
rank_A = np.linalg.matrix_rank(A)
print(f"Matrix A:\n{A}")
print(f"Rank: {rank_A} (full rank voor 2x2 matrix)")

# Rank deficient matrix
B = np.array([[1, 2], [2, 4]])
rank_B = np.linalg.matrix_rank(B)
print(f"\nMatrix B:\n{B}")
print(f"Rank: {rank_B} (rank deficient!)")

# Grotere matrix
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rank_C = np.linalg.matrix_rank(C)
print(f"\nMatrix C:\n{C}")
print(f"Rank: {rank_C} (rank deficient voor 3x3 matrix)")

Matrix A:
[[1 2]
 [3 4]]
Rank: 2 (full rank voor 2x2 matrix)

Matrix B:
[[1 2]
 [2 4]]
Rank: 1 (rank deficient!)

Matrix C:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank: 2 (rank deficient voor 3x3 matrix)


### Array Reshaping voor Lineaire Algebra

Vaak moeten we arrays hervormen voor matrix operaties:

In [161]:
# 1D array naar column vector
v = np.array([1, 2, 3, 4])
print(f"Original 1D array: {v} (shape: {v.shape})")

# Verschillende manieren om een column vector te maken
col_vector1 = v.reshape(-1, 1)
col_vector2 = v[:, np.newaxis]
col_vector3 = np.expand_dims(v, axis=1)

print(f"\nColumn vector (reshape): \n{col_vector1} (shape: {col_vector1.shape})")
print(f"\nColumn vector (newaxis): \n{col_vector2} (shape: {col_vector2.shape})")
print(f"\nColumn vector (expand_dims): \n{col_vector3} (shape: {col_vector3.shape})")

# Row vector
row_vector = v.reshape(1, -1)
print(f"\nRow vector: {row_vector} (shape: {row_vector.shape})")

# Flatten een matrix terug naar 1D
matrix = np.array([[1, 2], [3, 4]])
flattened = matrix.flatten()
print(f"\nMatrix:\n{matrix}")
print(f"Flattened: {flattened} (shape: {flattened.shape})")

Original 1D array: [1 2 3 4] (shape: (4,))

Column vector (reshape): 
[[1]
 [2]
 [3]
 [4]] (shape: (4, 1))

Column vector (newaxis): 
[[1]
 [2]
 [3]
 [4]] (shape: (4, 1))

Column vector (expand_dims): 
[[1]
 [2]
 [3]
 [4]] (shape: (4, 1))

Row vector: [[1 2 3 4]] (shape: (1, 4))

Matrix:
[[1 2]
 [3 4]]
Flattened: [1 2 3 4] (shape: (4,))


## Samenvatting

Dit overzicht heeft de belangrijkste aspecten van numpy behandeld die je nodig hebt voor machine learning en lineaire algebra. Numpy biedt:

- Efficiënte array operaties
- Broadcasting voor flexibele berekeningen
- Uitgebreide lineaire algebra functies
- Tools voor matrix manipulatie en analyse

Voor meer informatie, bekijk de [numpy reference](http://docs.scipy.org/doc/numpy/reference/).